// Kell's Stop — simple layout (fuel platform, no zone map)

export const LAYOUT = {
  type:  'simple',
  theme: 'neutral',
  zones: [
    {
      id:          'dock',
      label:       'Fuel Depot & Repairs',
      description: 'Cheap fuel, rationing enforced. Basic hull work only.',
      services:    ['repair'],
      flavor: [
        "KELL'S STOP — OPEN PORT",
        '',
        'A fuel platform bolted to whatever was left of',
        'an old survey barge. The two tanks on the starboard',
        'side are older than the platform. Nobody knows',
        "whose they were. Kell doesn't talk about it.",
        '',
        '[ FUEL DEPOT ]',
        'Cheap fuel. Rationing is enforced.',
        'First come, first filled.',
        '',
        '[ FIELD REPAIRS ]',
        'Basic hull work only. Expect to pay.',
        "Don't expect it fast.",
      ],
      requiredStanding: null,
    },
    {
      id:          'trade',
      label:       'Trade Post',
      description: 'Surplus rations, alloys, machine parts.',
      services:    ['trade'],
      flavor: [
        '[ TRADE POST ]',
        '',
        'Outbound cargo accepted.',
        'Prices reflect the difficulty of the run.',
      ],
      requiredStanding: null,
    },
    {
      id:          'bounties',
      label:       'Bounty Board',
      description: 'Contracts posted by local operators.',
      services:    ['bounties'],
      flavor: [
        '[ BOUNTY BOARD ]',
        '',
        'A single screen, chipped at the corner.',
        'The contracts are real. The targets are not friendly.',
      ],
      requiredStanding: null,
    },
    {
      id:          'intel',
      label:       'Intel',
      description: 'Station history and local intelligence.',
      services:    ['intel'],
      flavor: [],
      requiredStanding: null,
    },
    {
      id:          'relations',
      label:       'Relations',
      description: 'Faction standings.',
      services:    ['relations'],
      flavor: [],
      requiredStanding: null,
    },
  ],
};
